name: Deploy Documentation 

on:
  push:
    branches:
      - main   
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ github.workspace }}/workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Friendly workspace
        run: mkdir -p $WORKSPACE 

      - name: Get FurnariusMark
        run: git clone https://github.com/ttd3v/FurnariusMark $WORKSPACE
      
      - name: Install FurnariusMark
        run: gcc -O3 $WORKSPACE/FurnariusMark/main.c -o ./FurnariusMark

      - name: Build documentation
        run: ./FurnariusMark -f ./docs/documentation.md -t FalcoTCP 

      - name: Polish for satisfy Github
        run: mv ./FalcoTCP.html ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

